server:
  port: "8005"
  secret: "mySecretKey"
  accessTokenExpireDuration: 2
  refreshTokenExpireDuration: 2
Databases:
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_CONNECTION: pgsql
  TIMEZONE: Africa/Lagos
  SSLMODE: disable
  USERNAME: postgres
  PASSWORD: password
  ADMIN_DB: admin
  AUTH_DB: auth
  NOTIFICATIONS_DB: notifications
  PAYMENT_DB: payment
  REMINDERS_DB: reminder
  SUBSCRIPTIONS_DB: subscription
  TRANSACTIONS_DB: transaction
  VERIFICATION_DB: verification
  CRON_DB: cron
  Migrate: true
Microservices:
  Admin: localhost:4000/v1/admin
  Auth: localhost:4000/v1/auth
  Boilerplate: localhost:4000/v1/boilerplate
  Cron: localhost:4000/v1/cron
  Feedback: localhost:4000/v1/feedback
  Internaldocs: localhost:4000/v1/internaldocs
  Notification: localhost:4000/v1/notifications
  Payment: localhost:4000/v1/payment
  Productlink: localhost:4000/v1/productlink
  Referral: localhost:4000/v1/referral
  Reminders: localhost:4000/v1/reminders
  Roles: localhost:4000/v1/roles
  Subscription: localhost:4000/v1/subscription
  Transactions: localhost:4000/v1/transactions
  Upload: localhost:4000/v1/upload
  Verification: localhost:4000/v1/verification
  Widget: localhost:4000/v1/widget
