server:
  port: "9000"
Databases:
  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_CONNECTION: pgsql
  TIMEZONE: Africa/Lagos
  SSLMODE: disable
  USERNAME: postgres
  PASSWORD: password
  ADMIN_DB: admin
  AUTH_DB: auth
  NOTIFICATIONS_DB: notifications
  PAYMENT_DB: payment
  REMINDERS_DB: reminder
  SUBSCRIPTIONS_DB: subscription
  TRANSACTIONS_DB: transaction
  VERIFICATION_DB: verification
  CRON_DB: cron
