---
version: "3.9"
services:
  auth:
    build:
      context: ./
    ports:
      - "8005:8005"
    expose:
      - 8015
    networks:
      - vesicash-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - vesicash-net

#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - ./grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
#      - grafana:/var/lib/grafana
#    networks:
#      - vesicash-net

volumes:
  grafana:

networks:
  vesicash-net:
    driver: bridge
