global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:

rule_files:

scrape_configs:
  - job_name: "auth"
    scrape_interval: 10s
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["auth:8015"]
