version: 2.1

executors:
  golang:
    docker:
      - image: cimg/go:1.20.1

jobs:
  install-dependencies:
    working_directory: ~/auth-ms
    executor: golang
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Verify installation
          working_directory: ./
          command: go mod verify
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
